import { createFileRoute } from "@tanstack/react-router";
import { BookOpen, HeartHandshake, Scale, ShieldCheck } from "lucide-react";
export const Route = createFileRoute("/about")({
  head: () => ({ meta: [
    { title: "About Sattva — Responsible Wellness Education" }, { name: "description", content: "How Sattva presents traditional wellness information responsibly and safely." },
    { property: "og:title", content: "About Sattva" }, { property: "og:description", content: "Traditional wisdom, modern context, and safety-first wellness education." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: AboutPage,
});
function AboutPage() { const values = [[BookOpen,"Clear education","Short, accessible explanations without promises or miracle claims."],[Scale,"Balanced context","Traditional perspectives are clearly separated from modern medical explanations."],[ShieldCheck,"Safety first","Every guide highlights interactions, uncertainty, and signs that need medical care."],[HeartHandshake,"Complementary by design","Wellness practices sit alongside—not instead of—qualified healthcare."] ] as const; return <div className="mx-auto max-w-5xl px-5 py-16 sm:px-6 sm:py-24"><p className="text-xs font-bold uppercase tracking-widest text-primary">About Sattva</p><h1 className="mt-3 font-display text-5xl font-semibold sm:text-7xl">Tradition, without the overpromises.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Sattva is a modern educational guide to Ayurveda and complementary wellness. It helps you explore traditions thoughtfully while keeping evidence, personal context, and medical safety visible.</p><div className="mt-14 grid gap-4 sm:grid-cols-2">{values.map(([Icon,title,desc]) => <article key={title} className="rounded-card border border-border bg-card p-6 shadow-card"><span className="grid size-11 place-items-center rounded-full bg-secondary text-primary"><Icon size={20}/></span><h2 className="mt-5 font-display text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{desc}</p></article>)}</div><section className="mt-14 border-l-4 border-primary pl-6"><h2 className="font-display text-3xl font-semibold">A note on sources</h2><p className="mt-3 leading-7 text-muted-foreground">This initial guide provides conservative, general educational summaries rather than individualized advice. Scientific evidence changes over time. Confirm decisions with qualified healthcare professionals and trusted, current clinical resources.</p></section></div>; }
