/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as ConditionsSlugRouteImport } from './routes/conditions/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConditionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/wellness': typeof WellnessRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/wellness': typeof WellnessRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/wellness': typeof WellnessRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/conditions'
    | '/favorites'
    | '/wellness'
    | '/conditions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/conditions'
    | '/favorites'
    | '/wellness'
    | '/conditions/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/conditions'
    | '/favorites'
    | '/wellness'
    | '/conditions/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConditionsRoute: typeof ConditionsRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  WellnessRoute: typeof WellnessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof ConditionsRoute
    }
  }
}

interface ConditionsRouteChildren {
  ConditionsSlugRoute: typeof ConditionsSlugRoute
}

const ConditionsRouteChildren: ConditionsRouteChildren = {
  ConditionsSlugRoute: ConditionsSlugRoute,
}

const ConditionsRouteWithChildren = ConditionsRoute._addFileChildren(
  ConditionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConditionsRoute: ConditionsRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  WellnessRoute: WellnessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
